springdoc:
  api-docs:
    enabled: true # If you want to disable this feature, specify false
  swagger-ui:
    enabled: true # ditto

libs:
  bearer-token:
    issuer: tecchu11
    expire-after: PT24H
    secret-key: 404E635266556A586E3272357538782F
