server:
  shutdown: graceful

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - shutdown
          - health
          - openapi
          - swagger-ui
  server:
    port: 8880
    address: "127.0.0.1"
