springdoc:
  api-docs:
    enabled: true
  default-consumes-media-type: application/json
  show-actuator: false
  swagger-ui:
    enabled: true
    supportedSubmitMethods:
      - get
      - post
      - put
      - delete
  use-management-port: true

libs:
  bearer-token:
    issuer: tecchu11
    expire-after: PT24H
    secret-key: 404E635266556A586E3272357538782F
