server:
  shutdown: graceful

springdoc:
  default-consumes-media-type: application/json
  show-actuator: true
  swagger-ui:
    supportedSubmitMethods:
      - get
      - post
      - put
      - delete
  use-management-port: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - openapi
          - swagger-ui
  server:
    port: 8880
    address: "127.0.0.1"
