version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/buildSrc/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/api/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/web/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/common/"
    schedule:
      interval: "weekly"
