version: '3'

services:
  todo-mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: todo-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/volumes/mysql/todo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/volumes/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/volumes/mysql/todo/data:/var/lib/mysql
    ports:
      - "13306:3306"
