name: Build Image
description: Login ghcr and push built image

inputs:
  github-token:
    description: Login token for ghcr
    required: true
  build-target-module:
    description: Build target module name
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"
        cache: "gradle"

    - name: Login ghcr
      shell: bash
      run: |
        echo "${{ inputs.github-token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Image
      shell: bash
      run: |
        ./gradlew ${{ inputs.build-target-module }}:jib --no-daemon -PgitHash=${{ github.sha }}
