name: Build Image

inputs:
  build-target-module:
    description: Build target module name
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'gradle'

    - name: Login ghcr
      shell: bash
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Image
      shell: bash
      run: |
        echo ${{ inputs.build-target-module}}
