[versions]
mybatis = "2.2.0"

[libraries]
spring-mybatis = { module = "org.mybatis.spring.boot:mybatis-spring-boot-starter", version.ref = "mybatis" }
spring-mybatis-test = { module = "org.mybatis.spring.boot:mybatis-spring-boot-starter-test", version.ref = "mybatis" }
kulid = "com.github.guepardoapps:kulid:2.0.0.0"
logstash-logback-encoder = "net.logstash.logback:logstash-logback-encoder:7.0.1"
testcontainers-mysql = "org.testcontainers:mysql:1.16.2"
