spring:
  profiles:
    active: local
    group:
      local:
        - common

management:
  server:
    port: 8880
    address: "127.0.0.1"

mybatis:
  configuration:
    map-underscore-to-camel-case: true
