spring:
  profiles:
    active: local
    group:
      local:
       - common

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.example.todo.infrastructure.configuration.typehandler
