spring:
  profiles:
    active: local

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.example.todo.configuration.typehandler

app:
  logging:
    log-dir: ${user.home}/logs/app/
    log-name: todo-api.log
    max-history: 31
