version: '3'

services:
  todo-mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: todo-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./volumes/mysql/todo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./volumes/mysql/conf.d:/etc/mysql/conf.d
      - ./volumes/mysql/todo/data:/var/lib/mysql
    ports:
      - "13306:3306"
