spring:
  profiles:
    active: local
    group:
      local:
        - common
  rest-template:
    default:
      read-timeout: 5000
      connect-timeout: 5000

server:
  shutdown: graceful

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - shutdown
          - health
  server:
    port: 8881
    address: "127.0.0.1"
