spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 600000
      max-lifetime: 1800000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
