complexity:
  LongParameterList:
    active: true
    functionThreshold: 10
    constructorThreshold: 10
    ignoreDefaultParameters: false
    ignoreDataClasses: true
    ignoreAnnotatedParameter: []

empty-blocks:
  EmptyFunctionBlock:
    active: true
    excludes: ["**/test/**"]

performance:
  SpreadOperator:
    active: true
    excludes: ["**/TodoApplication.kt"]
