name: Auto Build Image

on:
  pull_request:
    branches:
      - main
#    paths:
#      - 'api'
#      - 'web'
#      - 'common'

jobs:
  build-image:
    strategy:
      matrix:
        module: [ 'api', 'web' ]
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: ./.github/workflows/composite/build-image
        with:
          build-target-module: ${{ matrix.module }}
