name: Auto Build Image

on:
  push:
    branches:
      - main

jobs:
  build-image:
    strategy:
      matrix:
        module: [ 'api', 'web' ]
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@v3

      - name: Build ${{ matrix.module }} image
        uses: ./.github/workflows/composite/build-image
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-target-module: ${{ matrix.module }}
