name: Auto Deletion for GHCR

on:
  workflow_run:
    workflows:
      - Auto Build Image
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Print on failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        shell: bash
        run: |
          echo 'Triggering workflow ${{ github.event.workflow_run.name }} failed'
      - name: Delete old image on success
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'todo-api'
          package-type: 'container'
          min-versions-to-keep: 2
