name: CD

on:
  workflow_dispatch:
    inputs:
      project:
        type: choice
        description: select target project
        required: true
        options:
          - web
          - api

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    environment: dev
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: checkout source
        uses: actions/checkout@v3
      - name: set up jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: login ghcr
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: gradle jib --no-daemon
        run: |
          ./gradlew ${{ github.event.inputs.project }}:jib --no-daemon -Djib.to.tags=${{ github.sha }}

      - name: echo success
        if: success()
        run: echo success

      - name: echo failure
        if: failure()
        run: echo failure
