name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: checkout source
        uses: actions/checkout@v3

      - name: set up jdk 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'

      - name: gradle check
        run: ./gradlew check --no-daemon
