name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: run kotlint
        run: ./gradlew ktlintCheck

  static-analisys:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: run kotlint
        run: ./gradlew detekt

  unit-test:
    needs:
      - lint
      - static-analisys
    runs-on: ubuntu-latest
    steps:
      - name: run kotlint
        run: ./gradlew test
