name: CI

on: pull_request

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Tokyo"
    steps:
      - name: checkout source
        uses: actions/checkout@v3

      - name: set up jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: gradle check
        run: ./gradlew check --no-daemon
