name: Notify

on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigered by workflow failed
        run: |
          echo 'Workflow ${{ github.event.workflow_run.name }} is ${{ github.event.workflow_run.conclusion }}'
